models/User.php
<?php

namespace app\models;

use app\components\MyUploadedFile;
use DateTime;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\UploadedFile;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $user_type тип
 * @property string $login Логин
 * @property string $name ФИО
 * @property string $email email
 * @property string $phone телефон
 * @property string $type тип пользователя
 * @property string $birth_date дата рождения
 * @property int $city_id город
 * @property int $work_city_id город выполненя работ
 * @property int $position_id Должность
 * @property int $role_id Роль
 * @property int $inn Роль
 * @property string $avatar Аватар
 * @property string $password_hash Зашифрованный пароль
 * @property int $access Доступ
 * @property int $is_deletable Можно удалить или нельзя
 * @property string $created_at
 * @property string $of_name
 * @property string $address
 *
 * @property UploadedFile $file
 *
 * @property Contract[] $contracts
 * @property Scan[] $scans
 * @property City $city
 * @property Position $position
 * @property Role $role
 * @property City $workCity
 */
class User extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface, \rmrevin\yii\module\Comments\interfaces\CommentatorInterface
{
    const SCENARIO_DEFAULT = 'default';
    const SCENARIO_EDIT = 'edit';

    public $password;

    public $user_type;

    public $listFile;

    public $file;

    private $oldPasswordHash;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        return [
            self::SCENARIO_DEFAULT => [
                'name', 'login', 'type', 'is_deletable', 'user_type',
                'inn', 'password', 'password_hash', 'role_id',
                'phone','address','of_name','listFile','birth_date','city_id','avatar','hour_cost', 'experience_rating', 'year_experience'],
            self::SCENARIO_EDIT => [
                'name', 'login', 'type', 'is_deletable', 'password',
                'inn', 'password_hash', 'role_id', 'city_id',
                'position_id', 'phone', 'address', 'of_name', 'birth_date', 'listFile', 'avatar','hour_cost', 'experience_rating', 'year_experience'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['login', 'name'], 'required'],
            [['password'], 'required', 'on' => self::SCENARIO_DEFAULT],
            ['birth_date', function(){
                if($this->birth_date > date('Y-m-d') or strlen($this->birth_date) > 10){
                    $this->addError('birth_date', 'Некорректная дата');
                    return false;
                }
            }],
            [['listFile',], 'validateListFile'],
            ['login', 'email'],
            [['login'], 'unique'],
            ['file', 'file'],
            [['role', 'access', 'is_deletable'], 'integer'],
            [['login', 'password_hash', 'password', 'name','type', 'inn', 'address', 'avatar', 'of_name','hour_cost', 'experience_rating', 'year_experience'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeDelete()
    {
        parent::beforeDelete();

        $uid = Yii::$app->user->identity->id;

        if($uid == $this->id)
        {
            Yii::$app->session->setFlash('error', "Вы авторизованы под пользователем «{$this->login}». Удаление невозможно!");
            return false;
        }

        if($this->is_deletable == false)
        {
            Yii::$app->session->setFlash('error', "Этот пользователь не может подлежать удалению. Удаление невозможно!");
            return false;
        } else {
            return true;
        }
    }

    public function getCommentatorAvatar()
    {
        return '/'.$this->getRealAvatar();
    }

    public function getCommentatorName()
    {
        return $this->name;
    }

    public function getCommentatorUrl()
    {
        return ['user/view', 'id' => $this->id]; // or false, if user does not have a public page
    }

    /**
     * @param string $attribute
     */
    public function validateListFile($attribute)
    {
        foreach($this->$attribute as $index => $row) {
            if ($row['name'] == null) {
                $key = $attribute . '[' . $index . '][name]';
                $this->addError($key, 'Обязательное для заполненния');
            }
            foreach ($_FILES['User']['name'][$attribute] as $indexFile => $file){
                if($file['file_new'] == null){
                    $key = $attribute . '[' . $index . '][file_new]';
                    $this->addError($key, 'Обязательное для заполненния');
                }
            }
        }
    }

    /**
     * @param string $action
     * @return bool
     */
    public function can($action)
    {
        if(Yii::$app->user->identity->role_id != null){
            $role = Role::findOne(Yii::$app->user->identity->role_id);

            if($role){
                if(isset($role->$action)){
                    return $role->$action == 1;
                }
            }
        }
        return false;
    }

    /**
     * @return string
     */
    public function getRealAvatar()
    {
        return $this->avatar != null ? $this->avatar : 'img/nouser.png';
    }

    /**
     * @return bool
     */
    public function isSuperAdmin()
    {
//        return $this->role === self::ROLE_ADMIN;
    }

    /**
     * @inheritdoc
     */
    public function afterFind()
    {
        $this->oldPasswordHash = $this->password_hash;
    }


    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if($this->file != null){
                $fileName = Yii::$app->security->generateRandomString();
                if(is_dir('upload') == false){
                    mkdir('upload');
                }
                $path = "uploads/{$fileName}.{$this->file->extension}";
                $this->file->saveAs($path);
                if($this->file != null && file_exists($this->file)){
                    unlink($this->file);
                }
                $this->avatar = $path;
            }

            if ($this->isNewRecord) {
                $this->created_at = date('Y-m-d H:i:s');
            }
            if($this->password != null){
                $this->password_hash = Yii::$app->security->generatePasswordHash($this->password);
            } else {
                $this->password_hash = $this->oldPasswordHash;
            }

            try {
                Yii::$app->mailer->compose()
                    ->setTo($this->login)
                    ->setFrom('hh.notify@yandex.ru')
                    ->setSubject('Вы зарегистрированы')
                    ->setHtmlBody("Ваш логин: {$this->login}<br> Ваш пароль: {$this->password}<br><a href='".Url::toRoute(['site/login'], true)."'>Войти в систему</a>")
                    ->send();
            } catch (\Exception $e)
            {
                Yii::warning('Email sending failed');
            }

            return true;
        }
        return false;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);



        if ($this->user_type != null) {
            $allSubs = UserType::find()->where(['user_id' => $this->id])->all();
            foreach ($allSubs as $sub){
                if (array_search($sub, $this->user_type) !== false){
                    continue;
                }else{
                    $sub->delete();
                }
            }
            foreach ($this->user_type as $subgroup) {
                $subgroup2 = UserType::find()->where(['user_id' => $this->id, 'type_id' => $subgroup])->one();
                if (!$subgroup2) {
                    (new UserType([
                        'type_id' => $subgroup,
                        'user_id' => $this->id
                    ]))->save(false);
                }
            }

        }

        if($this->listFile != null){
            $files = MyUploadedFile::getInstancesByName('listFile', true);

            $files = array_combine(ArrayHelper::getColumn($this->listFile, 'name'), $files);
            foreach ($files as $name => $file){
                /** @var $file MyUploadedFile */

                $path = Yii::$app->security->generateRandomString();
                $path = "uploads/{$path}.$file->extension";

                $file->saveAs($path);

                $scan = new Scan([
                    'name' => $name,
                    'link' => $path,
                    'user_id' => $this->id,
                    'author_id' => Yii::$app->user->getId(),
                ]);
                $scan->save(false);
            }
        }
        $this->listFile = null;


    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'login' => 'Email',
            'name' => 'ФИО',
            'email' => 'Email',
            'phone' => 'Номер телефона ',
            'type' => 'Тип пользователя',
            'birth_date' => 'Дата рождения',
            'city_id' => 'Город',
            'position_id' => 'Должность',
            'role_id' => 'Роль сотрудника',
            'file' => 'Фотография',
            'avatar' => 'Фотография',
            'password_hash' => 'Password Hash',
            'access' => 'Доступ',
            'is_deletable' => 'Можно ли удалять',
            'created_at' => 'Дата создания',
            'inn' => 'ИНН',
            'user_type' => 'Типы выполняемых работ',
            'address' => 'Адрес офиса',
            'of_name' => 'Название юридического лица',
            'hour_cost' => 'Стоимость в час',
            'experience_rating' => 'Оценка опыта',

models/UserType.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user_type".
 *
 * @property int $id
 * @property int $user_id id пользователя
 * @property int $type_id id типа
 */
class UserType extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'type_id'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'id пользователя',
            'type_id' => 'id типа',
        ];
    }
}

views/user/_columns.php
<?php

use app\models\City;
use app\models\Role;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'type',
        'content' =>function($data){
//            $type = intval($data->type);
            if ($data->type == '0') {
                return 'Штатный';
            }
            if ($data->type == '1') {
                return 'Внештатный';
            }
            if ($data->type == '2') {
                return 'Подрядчик';
            }
            return 'не заданно';
        },

        'filter'=>array(
            '0' => 'Штатный',
            '1' => 'Внештатный',
            '2' => 'Подрядчик'
        ),

    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'city_id',
        'value'=>'city.name',
        'filter' => ArrayHelper::map(City::find()->asArray()->all(), 'id', 'name'),
        'filterType' => GridView::FILTER_SELECT2,
        'filterWidgetOptions' => [
            'options' => ['prompt' => ''],
            'pluginOptions' => ['allowClear' => true],
        ],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'role_id',
        'value'=>'role.name',
        'filter' => ArrayHelper::map(Role::find()->asArray()->all(), 'id', 'name'),
        'filterType' => GridView::FILTER_SELECT2,
        'filterWidgetOptions' => [
            'options' => ['prompt' => ''],
            'pluginOptions' => ['allowClear' => true],
        ],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
        'content' => function($model){
            return Html::a($model->name, ['view', 'id' => $model->id], ['data-pjax' => '0']);
        }
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'phone',
//    ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'birth_date',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'city_id',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'work_city_id',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'position_id',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'role_id',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'avatar',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'password_hash',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'access',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'is_deletable',
    // ],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'created_at',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'template' => '{view}{update}{delete}',
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) {
                return Url::to([$action,'id'=>$key]);
        },

//        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Изменить', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить',
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Вы уверены?',
                          'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'],
    ],

];

views/user/_order_columns.php
<?php


use app\models\Contract;
use app\models\OrderStatus;
use app\models\OrderWorkType;

use app\models\WorkType;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'template' => '{addtask} {view} {update} {delete}',
        'buttons' => [
            'addtask' => function($url, $model){
                return   Html::a('<i class="fa fa-plus"></i>', ['task/create', 'order_id' => $model->id, 'containerPjaxReload' => '#pjax-container-info-container'],
                    ['role'=>'modal-remote','title'=> 'Добавить Задачу']);
            }
        ],
//        'urlCreator' => function($action, $model, $key, $index) {
//            return Url::to(['order/'.$action,'id'=>$key, 'contract_id' => $model->contract_id, 'containerPjaxReload' => '#pjax-container-info-container']);
//        },
//        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Изменить', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Удалить',
            'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
            'data-request-method'=>'post',
            'data-toggle'=>'tooltip',
            'data-confirm-title'=>'Вы уверены?',
            'data-confirm-message'=>'Вы действительно хотите удалить данный элемент?'],
    ],

//    [
//        'class' => 'kartik\grid\SerialColumn',
//        'width' => '30px',
//    ],
//        // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'id',
    //
    [
        'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '50px',
        'value' => function ($model, $key, $index, $column) {
            return GridView::ROW_COLLAPSED;
        },
        'detailUrl' => function ($model) {
//            return Url::toRoute(['view', 'id' => $model->id]);
        },
        'detail' => function ($model, $key, $index, $column) {
            $filesSearchModel = new \app\models\TaskSearch();
            $filesDataProvider = $filesSearchModel->search([]);
            $filesDataProvider->query->andWhere(['order_id' => $model->id]);

            return \Yii::$app->controller->renderPartial('_task-table', [
                'model' => $model,
                'searchModel' => $filesSearchModel,
                'dataProvider' => $filesDataProvider,
                'model' => $model,
            ]);
        },
        'headerOptions' => ['class' => 'kartik-sheet-style'],
        'expandOneOnly' => true
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'hours_plane',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'hours_fact',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'order_status_id',
        'content' => function($data){
            $status = ArrayHelper::getColumn(OrderStatus::find()->where(['id' => $data->order_status_id])->all(), 'name');
            return implode('',$status);

        },
        'filter' => ArrayHelper::map(OrderStatus::find()->asArray()->all(), 'id', 'name'),
        'filterType' => GridView::FILTER_SELECT2,
        'filterWidgetOptions' => [
            'options' => ['prompt' => ''],
            'pluginOptions' => ['allowClear' => true],
        ],
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'order_date',
    ],

//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'order_deadline',
//        'filterInputOptions' => ['class' => 'form-control', 'type' => 'date'],
//    ],



    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'expired',
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'scan_added',
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'related_orders',
//    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'comment',
        'width' => '10%',
    ],
//    [
//        'attribute'=>'construction_type',
//        'label' => 'Статус',
//        'filter'=>array(
//            'Модернизация' => 'Модернизация',
//            'Строительство' => 'Строительство',
//        ),
        //
//        'content' => function($model){
//            $icon = '';
//
//            if($model->construction_type == 'Модернизация'){
//                $icon = '<i class="fa fa-wrench" style="font-size: 15px;"></i>';
//            } else if($model->construction_type == 'Строительство') {
//                $icon = '<i class="fa fa-book" style="font-size: 15px;"></i>';
//            }
//
//            return $icon;
//        },
//        'width' => '4%',
//        'hAlign' => GridView::ALIGN_CENTER,
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'ams_type_id',
//        'content' => function($data){
//            $ams = ArrayHelper::getColumn(AmsType::find()->where(['id' => $data->ams_type_id])->all(), 'name');
//            return implode('',$ams);
//
//        },
//        'filter' => ArrayHelper::map(AmsType::find()->asArray()->all(), 'id', 'name'),
//        'filterType' => GridView::FILTER_SELECT2,
//        'filterWidgetOptions' => [
//            'options' => ['prompt' => ''],
//            'pluginOptions' => ['allowClear' => true],
//        ],
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'placement_id',
//        'content' => function($data){
//            $placement = ArrayHelper::getColumn(Placement::find()->where(['id' => $data->placement_id])->all(), 'name');
//            return implode('',$placement);
//
//        },
//        'filter' => ArrayHelper::map(Placement::find()->asArray()->all(), 'id', 'name'),
//        'filterType' => GridView::FILTER_SELECT2,
//        'filterWidgetOptions' => [
//            'options' => ['prompt' => ''],
//            'pluginOptions' => ['allowClear' => true],
//        ],
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'author_id',
//    ],










];

views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

?>
<div class="user-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/user/order-index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset;
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\HistorySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $candidateId integer */

CrudAsset::register($this);

?>
<?=GridView::widget([
    'id'=>'crud-order-datatable',
    'dataProvider' => $dataProvider,
//            'filterModel' => $searchModel,
    'pjax'=>true,
    'columns' => require(__DIR__.'/_order_columns.php'),
    'striped' => true,
    'condensed' => true,
    'responsive' => true,
//    'panel' => [
//        'headingOptions' => ['style' => 'display: none;'],
//        'after'=>'',
//    ]
])?>

views/user/reset-password-form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\forms\ResetPasswordForm */
/* @var $form ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'newPassword') ?>
<?= $form->field($model, 'repeatPassword') ?>

<?php if(!Yii::$app->request->isAjax): ?>
    <div class="form-group">
        <?= Html::submitButton('Изменить', ['class' => 'btn btn-primary']) ?>
    </div>
<?php endif; ?>

<?php ActiveForm::end(); ?>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */
?>
<div class="user-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use app\models\City;
use app\models\Subgroups;
use app\models\UserKind;

use app\models\UserType;
use app\models\WorkKind;
use app\models\WorkType;
use yii\bootstrap\Modal;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

?>
<div class="user-view">
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">Информация</h4>
            <div class="panel-heading-btn" style="margin-top: -20px;">
                <?= Html::a('<span class="glyphicon glyphicon-pencil "></span>', ['user/update', 'id' => $model->id, 'containerPjaxReload' => '#pjax-user-info-container'], ['role' => 'modal-remote']) ?>
            </div>
        </div>
        <div class="panel-body">
 
    <?php Pjax::begin(['id' => 'pjax-user-info-container', 'enablePushState' => false]); ?>
            <div class="row">
                <div class="col-md-2">
                    <img src="<?=Url::toRoute(['/'.$model->realAvatar])?>" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
                <div class="col-md-5">
                    <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                    [
                    'attribute' => 'type',
                    'value' => function($data){
                    $attrName = '';
                    if ($data['type'] == 0){
                    return $attrName = 'Штатный';
                    }
                    if ($data['type'] == 1){
                    return $attrName = 'Внештатный';
                    }else{
                    return $attrName = 'Подрядчик';
                    }

                    }
                    ],
                    'name',
                    'login:email',
                    [
                    'attribute' => 'city_id',
                    'value' => ArrayHelper::getValue($model->getCity()->one(),'name')
                    ],
                        [
                            'attribute' => 'address',
                            'visible' => $model->type == 2,
                        ],
                        [
                            'attribute' => 'of_name',
                            'visible' => $model->type == 2,
                        ],
                    [
                    'attribute' => 'user_type',
                    'visible' =>in_array($model->type,[2, 1]),
                    'value' => function($data){
                    $workTypes = ArrayHelper::getColumn(UserType::find()->where(['user_id' => $data->id ])->all(), 'type_id');
                    $workTypes =ArrayHelper::getColumn(WorkType::find()->where(['id' => $workTypes])->all(), 'name');
                    $workTypes = implode(', ', $workTypes);
                    return $workTypes;
                    }
                    ],
                    ],
                    ]) ?>
                </div>



                <div class="col-md-5">
                    <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                    [
                    'attribute' => 'role_id',
                    'value' => ArrayHelper::getValue($model->getRole()->one(),'name')
                    ],
                    'birth_date',
                    'phone',
                    [
                        'attribute' => 'address',
                        'visible' => $model->type == 2,
                    ],
                    [
                    'attribute' => 'user_kind',
                        'visible' =>in_array($model->type,[2, 1]),
                    'value' => function($data){
                    $c = ArrayHelper::getColumn(UserKind::find()->where(['user_id' => $data->id])->all(), 'kind_id');
                    $kinds = ArrayHelper::getColumn(Subgroups::find()->where(['id' => $c])->all(), 'name');
                    $kinds = implode(', ', $kinds);
                    return $kinds;
                    }
                    ]
                    ],
                    ]) ?>
                </div>


            </div>



        </div>
    <?php Pjax::end(); ?>



    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title">Заказы</h4>
                    <div class="panel-heading-btn" style="margin-top:-20px;overflow-y: auto;">
                        <?= Html::a('<span class="glyphicon glyphicon-plus btn-circle"></span>', ['order/create', 'containerPjaxReload' => '#pjax-container-info-container'],
                            ['role'=>'modal-remote','title'=> 'Добавить спринт','class'=>'btn btn-warning btn-xs'])?>
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning"  data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>


                <div class="panel-body">
                    <div class="col-md-12">

                        <?= $this->render('@app/views/user/order-index', [
                            'searchModel' => $orderSearchModel,
                            'dataProvider' => $orderDataProvider,
                            'user_id' => $model->id,
                        ]) ?>
                    </div>
                </div>
            </div>

        </div>
    </div>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-inverse">
                    <div class="panel-heading">
                        <h4 class="panel-title">Документы</h4>
                        <div class="panel-heading-btn" style="margin-top: -20px;">
                            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                        </div>
                    </div>


                    <div class="panel-body" style="height: 500px; overflow-y: auto;">
                        <div class="col-md-12">

                        <?= $this->render('@app/views/user/scan_index.php', [
                            'searchModel' => $scanSearchModel,
                            'dataProvider' => $scanDataProvider,
                            'user_id' => $model->id,
                        ]) ?>
                    </div>
                    </div>
                </div>
            </div>


            <div class="col-md-12">
                <div class="panel panel-inverse">
                    <div class="panel-heading">
                        <h4 class="panel-title">Отзывы</h4>
                    </div>
                    <div class="panel-body" style="height: 500px; overflow-y: auto;">
                        <div class="alert alert-success">
                            <h5>Проект 1</h5>
                            <p>Отлично справился</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    'options' => ['class' => 'fade modal-slg'],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>